service: aws-lunch-bot

provider:
  name: aws
  profile: vipul
  runtime: python3.6

functions:
  post_lunch_menu:
    handler: main.call
    events:
    - schedule:
        rate: cron(0 8 ? * 1-5 *)
        enabled: true

package:
  exclude:
    - .venv/**
    - .git/**
    - __pycache__/**
    - node_modules/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements: 
    dockerizePip: non-linux
